/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zdcfinalproject;

/**
 *
 * @author Interact
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        mnuMenuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFileNew = new javax.swing.JMenu();
        mnuFileNewOrder = new javax.swing.JMenuItem();
        mnuFileNewCustomer = new javax.swing.JMenuItem();
        mnuDisplay = new javax.swing.JMenu();
        mnuDisplayCoffees = new javax.swing.JMenuItem();
        mnuDisplayCustomers = new javax.swing.JMenuItem();
        mnuDisplayOrders = new javax.swing.JMenuItem();
        mnuDatabase = new javax.swing.JMenu();
        mnuDatabaseCreate = new javax.swing.JMenuItem();
        mnuDatabaseDrop = new javax.swing.JMenuItem();
        mnuDatabasePopulate = new javax.swing.JMenuItem();
        mnuDatabaseReset = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zdcfinalproject/Coffee.png"))); // NOI18N

        mnuFile.setText("File");

        mnuFileNew.setText("New");

        mnuFileNewOrder.setText("Order");
        mnuFileNew.add(mnuFileNewOrder);

        mnuFileNewCustomer.setText("Customer");
        mnuFileNew.add(mnuFileNewCustomer);

        mnuFile.add(mnuFileNew);

        mnuMenuBar.add(mnuFile);

        mnuDisplay.setText("Display");

        mnuDisplayCoffees.setText("Coffees");
        mnuDisplay.add(mnuDisplayCoffees);

        mnuDisplayCustomers.setText("Customers");
        mnuDisplay.add(mnuDisplayCustomers);

        mnuDisplayOrders.setText("Orders by Customer");
        mnuDisplay.add(mnuDisplayOrders);

        mnuMenuBar.add(mnuDisplay);

        mnuDatabase.setText("Database");

        mnuDatabaseCreate.setText("Create Tables");
        mnuDatabase.add(mnuDatabaseCreate);

        mnuDatabaseDrop.setText("Drop Tables");
        mnuDatabase.add(mnuDatabaseDrop);

        mnuDatabasePopulate.setText("Populate Tables");
        mnuDatabase.add(mnuDatabasePopulate);

        mnuDatabaseReset.setText("Reset Tables");
        mnuDatabase.add(mnuDatabaseReset);

        mnuMenuBar.add(mnuDatabase);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenu mnuDatabase;
    private javax.swing.JMenuItem mnuDatabaseCreate;
    private javax.swing.JMenuItem mnuDatabaseDrop;
    private javax.swing.JMenuItem mnuDatabasePopulate;
    private javax.swing.JMenuItem mnuDatabaseReset;
    private javax.swing.JMenu mnuDisplay;
    private javax.swing.JMenuItem mnuDisplayCoffees;
    private javax.swing.JMenuItem mnuDisplayCustomers;
    private javax.swing.JMenuItem mnuDisplayOrders;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuFileNew;
    private javax.swing.JMenuItem mnuFileNewCustomer;
    private javax.swing.JMenuItem mnuFileNewOrder;
    private javax.swing.JMenuBar mnuMenuBar;
    // End of variables declaration//GEN-END:variables
}
